api_login_check:
  path: /auth
app.swagger_ui:
  path: /doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
